spring:
  mvc.view:
    prefix: /jsp/
    suffix: .jsp
  resources:
    static-locations: /html/
  datasource:
    username: marek
    password: marek
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/marektutorial
    hikari.maximum-pool-size: 1
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
